# Server configurations
server:
        host: "localhost"
        port: 8080

# Database credentials
database:
        user: "admin"
        pass: "nimda"
        name: "products"
        server: "product_management_db""
